apiVersion: v1
kind: Service
metadata:
  name: ng-auth-ui
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ng-auth-ui.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: http
    port: {{ .Values.service.port }}
    protocol: {{ .Values.service.protocol }}
    targetPort: {{ .Values.service.targetport }}
  selector:
    {{- include "ng-auth-ui.selectorLabels" . | nindent 4 }}
